package mobileshop.model;
// Generated Dec 4, 2013 3:57:57 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category")
public class Category{

    @Id
    @GeneratedValue
    @Column(name = "categoryID")
     private Integer categoryId;
    @Column(name = "categoryName")
     private String categoryName;
    @Column(name = "categoryPicture")
     private String categoryPictutre;
    
    public Category() {
    }

    public Category(String categoryName, String categoryPictutre) {
        this.categoryName = categoryName;
        this.categoryPictutre = categoryPictutre;
    }
   
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public String getCategoryPictutre() {
        return this.categoryPictutre;
    }
    
    public void setCategoryPictutre(String categoryPictutre) {
        this.categoryPictutre = categoryPictutre;
    }
}


