package mobileshop.model;
// Generated Dec 4, 2013 3:57:57 PM by Hibernate Tools 3.2.1.GA


import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order")
public class Order {
     @Id
    @GeneratedValue
    @Column(name = "orderID")
     private Integer orderId;
     @Column(name = "accountID")
     private String accountId;
     @Column(name = "orderdetailsID")
     private String orderdetailsId;
     @Column(name = "orderDate")
     private Timestamp orderDate;

    public Order() {
    }

	
    public Order(String accountId, String orderdetailsId, Timestamp orderDate) {
        this.accountId = accountId;
        this.orderdetailsId = orderdetailsId;
        this.orderDate = orderDate;
    }
    
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
   
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public String getAccountId() {
        return accountId;
    }
    
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }
    
    public String getOrderdetailsId() {
        return orderdetailsId;
    }
    
    public void setOrderdetailsId(String orderdetailsId) {
        this.orderdetailsId = orderdetailsId;
    }
    
    public void setOrderDate(Timestamp orderDate) {
        this.orderDate = orderDate;
    }
}


