package mobileshop.model;
// Generated Dec 4, 2013 3:57:57 PM by Hibernate Tools 3.2.1.GA

import java.sql.Timestamp;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Orderdetails generated by hbm2java
 */
@Entity
@Table(name = "orderDetails")
public class Orderdetails{

    @Id
    @GeneratedValue
    @Column(name = "orderDetailID")
     private int orderDetailId;
    
    @Column(name = "productID")
     private String productId;
    @Column(name = "orderDetailDate")
     private Timestamp orderDetailDate;
    @Column(name = "orderDetailProductCode")
     private String orderDetailProductCode;
    @Column(name = "orderDetailAmount")
     private int orderDetailAmount;
    @Column(name = "orderDetailPrice")
     private int orderDetailPrice;
    @Column(name = "orderDetailTotalPrice")
     private int orderDetailTotalPrice;
    
    public Orderdetails() {
    }

	
    public Orderdetails(int orderDetailId, String productId, Timestamp orderDetailDate, String orderDetailProductCode, int orderDetailAmount, int orderDetailPrice, int orderDetailTotalPrice) {
        this.orderDetailId = orderDetailId;
        this.productId = productId;
        this.orderDetailDate = orderDetailDate;
        this.orderDetailProductCode = orderDetailProductCode;
        this.orderDetailAmount = orderDetailAmount;
        this.orderDetailPrice = orderDetailPrice;
        this.orderDetailTotalPrice = orderDetailTotalPrice;
    }
   
    public int getOrderDetailId() {
        return this.orderDetailId;
    }
    
    public void setOrderDetailId(int orderDetailId) {
        this.orderDetailId = orderDetailId;
    }
   
    public Date getOrderDetailDate() {
        return this.orderDetailDate;
    }
    
    public String getOrderDetailProductCode() {
        return this.orderDetailProductCode;
    }
    
    public void setOrderDetailProductCode(String orderDetailProductCode) {
        this.orderDetailProductCode = orderDetailProductCode;
    }
    public int getOrderDetailAmount() {
        return this.orderDetailAmount;
    }
    
    public void setOrderDetailAmount(int orderDetailAmount) {
        this.orderDetailAmount = orderDetailAmount;
    }
    public int getOrderDetailPrice() {
        return this.orderDetailPrice;
    }
    
    public void setOrderDetailPrice(int orderDetailPrice) {
        this.orderDetailPrice = orderDetailPrice;
    }
    public int getOrderDetailTotalPrice() {
        return this.orderDetailTotalPrice;
    }
    
    public void setOrderDetailTotalPrice(int orderDetailTotalPrice) {
        this.orderDetailTotalPrice = orderDetailTotalPrice;
    }
}


