package mobileshop.model;
// Generated Dec 4, 2013 3:57:57 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product {

    @Id
    @GeneratedValue
    @Column(name = "productID")
     private Integer productId;
    @Column(name = "categoryID")
     private String categoryId;
    @Column(name = "productName")
     private String productName;
    @Column(name = "productCode")
     private String productCode;
    @Column(name = "productDescription")
     private String productDescription;
    @Column(name = "productPrice")
     private int productPrice;
    @Column(name = "productPicutre")
     private String productPicture;

    public Product() {
    }

	
    public Product(String categoryId, String productName, String productCode, String productDescription, int productPrice, String productPicture) {
        this.categoryId = categoryId;
        this.productName = productName;
        this.productCode = productCode;
        this.productDescription = productDescription;
        this.productPrice = productPrice;
        this.productPicture = productPicture;
    }
    
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }
    public int getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(int productPrice) {
        this.productPrice = productPrice;
    }
    public String getProductPicture() {
        return this.productPicture;
    }
    
    public void setProductPicture(String productPicture) {
        this.productPicture = productPicture;
    }

    /**
     * @return the categoryId
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * @param categoryId the categoryId to set
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
  
}


