package mobileshop.model;
// Generated Dec 4, 2013 3:57:57 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name = "promotion")
public class Promotion {

    @Id
    @GeneratedValue
    @Column(name = "promotionID")
     private int promotionId;
    @Column(name = "productID")
     private String productId;
    @Column(name = "promotionValue")
     private int promotionValue;

    public Promotion() {
    }

    public Promotion(int promotionId, String productId, int promotionValue) {
       this.promotionId = promotionId;
       this.productId = productId;
       this.promotionValue = promotionValue;
    }
   
    public int getPromotionId() {
        return this.promotionId;
    }
    
    public void setPromotionId(int promotionId) {
        this.promotionId = promotionId;
    }
    
    public int getPromotionValue() {
        return this.promotionValue;
    }
    
    public void setPromotionValue(int promotionValue) {
        this.promotionValue = promotionValue;
    }

    /**
     * @return the productId
     */
    public String getProductId() {
        return productId;
    }

    /**
     * @param productId the productId to set
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }
}


